CREATE TABLE Emp(
EmpID INT PRIMARY KEY,
Name VARCHAR(50),
DateOfBirth DATE,
JoinDate DATE);

SELECT * FROM EMP;

INSERT INTO Emp(EmpID, Name, DateOfBirth,JoinDate) VALUES
(1, 'Alice Johnson', '1985-05-20', '2010-06-15'),
(2, 'Bob Smith', 	'1990-08-10', '2015-09-01'),
(3, 'Charlie Brown', '1988-03-25', '2012-11-12'),
(4, 'Diana Prince', '1992-01-30', '2017-07-08'),
(5, 'Eve Adams', 	'1987-12-05', '2013-03-20');

--1. a) Current Date & Time:

SELECT CURRENT_TIMESTAMP AS TIMESTAMP;

--2. b) Calculate Age:

SELECT NAME,
       DATEDIFF(YEAR,DATEOFBIRTH,GETDATE()) AS AGE
FROM EMP;

--3. c) Calculate Experience:

SELECT NAME, 
    FLOOR(DATEDIFF(DAY,JOINDATE,GETDATE())/365.25) AS YEARSEXPERIENCE 
FROM EMP;

--4. d) Extract DOB Components:

SELECT NAME, YEAR(DATEOFBIRTH) AS BIRTHYEAR, MONTH(DATEOFBIRTH) AS BIRTHMONTH, DAY(DATEOFBIRTH) AS BIRTHDAY FROM EMP;

--5. e) Born in August:

SELECT NAME FROM EMP WHERE MONTH(DATEOFBIRTH) = 8;

--6. f) Upcoming Birthdays:

SELECT NAME FROM EMP
WHERE DATEADD(YEAR, YEAR(GETDATE()) - YEAR(DATEOFBIRTH), DATEOFBIRTH)
BETWEEN GETDATE() AND DATEADD(DAY, 30, GETDATE());
